default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: videosharing_dev
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: videosharing_test

production:
  <<: *default
  database: videosharing_production
