default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] + '_development' %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] + '_test' %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] + '_staging' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] + '_production' %>
